app:
  db:
    url: jdbc:sqlite:/home/jobender/Documents/Coding/Banking-Transaction-Dashboard/sql.db
    driverClassName: org.sqlite.JDBC
    #transactiondb
    user: sa
    #T4nSa3t1oNd8
    password: sa
    sql:
      files:
        setup: setup.sql

spring:
  datasource:
    url: jdbc:sqlite:/home/jobender/Documents/Coding/Banking-Transaction-Dashboard/sql.db
    driverClassName: org.sqlite.JDBC
    type:
